# Generated by Django 5.0.1 on 2024-08-07 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_no', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('balance', models.IntegerField(max_length=100)),
            ],
        ),
    ]
